apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: openvpnproxy
version: 0.1.0
sources:
- https://github.com/soarinferret/openvpn-proxy
icon: https://forums.openvpn.net/styles/openvpn/theme/images/ovpnlogo.png