apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openvpnproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openvpnproxy.name" . }}
    helm.sh/chart: {{ include "openvpnproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openvpnproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "openvpnproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - "NET_ADMIN"
          env:
          - name: HOSTIP
            value: {{ .Values.hostip  | quote }}
          - name: VPNCONF
            valueFrom:
              secretKeyRef:
                name: {{ template "openvpnproxy.fullname" . }}
                key: openvpn-conf
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ip route | grep 'via.*tun0'
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
