apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openvpnproxy.fullname" . }}
  labels:
    app: {{ template "openvpnproxy.name" . }}
    chart: {{ template "openvpnproxy.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  openvpn-conf: {{ .Values.vpnConf | b64enc | quote }}
  